//引入css
require("../../css/lib/reset.css");
require("../../css/common/global.less");
require("../../css/common/main.less");
require("../../css/common/grid.less");
require("../../css/common/header.less");
require("../../css/common/footer.less");
require("../../css/common/feature.less");
//引入js
require("../../js/components/header.js");
require("../../js/components/cookie.js");
